# Generated by Django 4.1.8 on 2023-04-17 15:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "Navigationsleiste",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            "button_page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "button_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="If the button page above is selected, that will be used first.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "item",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "button_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "button_url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="If the button page above is selected, that will be used first.",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "Header",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "HEADER",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            "SUBTITLE",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            "Button1",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "button1_page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "button1_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="If the button page above is selected, that will be used first.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "Button2",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "button2_page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "button2_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="If the button page above is selected, that will be used first.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "MasterImage",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "ImgAndText",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "button",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "button_page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "button_url",
                                            wagtail.blocks.URLBlock(
                                                help_text="If the button page above is selected, that will be used first.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "reverse",
                                            wagtail.blocks.BooleanBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=None,
                    ),
                ),
            ],
            options={"verbose_name": "Flex Page", "verbose_name_plural": "Flex Pages",},
            bases=("wagtailcore.page",),
        ),
    ]
